UK-Export-Finance/mdm-api

- .eslintrc.js
- .github/workflows/lint.yml
- README.md
- package-lock.json
- package.json
- src/config/database.config.ts
- src/database/index.ts
- src/database/mssql-database.module.ts
- src/database/redis-database.module.ts
- src/main.ts
- added ESLint as a required step on PR jobs
> chore: added ESLint as part of PR jobs

- .github/workflows/sca.yml
- .github/workflows/test.yml
- package-lock.json
- package.json
Test suites execution in GHA.
* Renamed npm scripts for consistency.
* `test.yml`: GHA responsible for executing unit test for `main` branch PRs.
> feat(unit-test): Unit testing on GHA

- package-lock.json
> chore(npm-update): dependencies update

- .env.sample
- src/constants/enums.ts
- src/constants/enums/products.ts
- src/constants/index.ts
- src/constants/products.ts
- src/modules/exposure-period/dto/get-exposure-period-query.dto.ts
- src/modules/premium-schedules/dto/create-premium-schedule.dto.ts
- test/exposure-period/exposure-period.api-test.ts
- test/premium-schedules/premium-schedules.api-test.ts
Lack of products related constants.
* Global enum introduction and consumption.
* `PRODUCTS` constants introduction and consumption.
* Enhanced test coverage.
* `.env.sample` comments
> feat(APIM-151): global enum introduction

- package-lock.json
> chore(npm-update): dependency update

- package-lock.json
Cross-realm object access in Webpack 5 has been flagged as a `High` vulnerability under `CVE-2023-28154`.
* Webpack updated to `5.76.2`.
* Regular dependencies updates.
> fix(CVE-2023-28154): webpack updated to 5.76.2

- src/modules/currencies/currencies.service.ts
- src/modules/currencies/entities/currency-exchange.entity.ts
- src/modules/markets/entities/market.entity.ts
- test/currencies/currencies.api-test.ts
- fixed: Currency Exchange End point Api differences in Node with Mulesoft (i.e. removed `errorCode` and `subCategory`
> fix(APIM-197): fixed currency exchange issues

- .github/workflows/deployment.yml
- .github/workflows/infrastructure.yml
- .husky/commit-msg
- package-lock.json
A generic deployment script
* Refer to the `TARGET` and `VERSION` from GH environment variables.
* Simplified YML scripts.
> fix(deployment): generic deployment script

- .github/workflows/deploy.sh
- .github/workflows/deployment.yml
- .github/workflows/lint.yml
- .github/workflows/sca.yml
- .github/workflows/test.yml
> refactor(iac): iac refactored

- .github/workflows/deployment.yml
Added missing AZ CLI argument for CA update.
> fix(iac): added missing argument

- .dockerignore
- Dockerfile
- src/main.ts
- src/modules/constants/constants.controller.test.ts
- src/modules/currencies/currencies.controller.test.ts
- src/modules/exposure-period/exposure-period.controller.test.ts
- src/modules/exposure-period/exposure-period.service.ts
- src/modules/interest-rates/interest-rates.controller.test.ts
- src/modules/premium-schedules/premium-schedules.controller.test.ts
- src/modules/sector-industries/sector-industries.controller.test.ts
- src/modules/yield-rates/yield-rates.controller.test.ts
> fix(mdm): reverted commit 5e1d74

- .dockerignore
- .github/workflows/lint.yml
- .github/workflows/sca.yml
- .github/workflows/test.yml
- Dockerfile
- README.md
- src/main.ts
- src/modules/constants/constants.controller.test.ts
- src/modules/currencies/currencies.controller.test.ts
- src/modules/exposure-period/exposure-period.controller.test.ts
- src/modules/exposure-period/exposure-period.service.ts
- src/modules/interest-rates/interest-rates.controller.test.ts
- src/modules/premium-schedules/premium-schedules.controller.test.ts
- src/modules/sector-industries/sector-industries.controller.test.ts
- src/modules/yield-rates/yield-rates.controller.test.ts
Fix MDM CA run-time error
* Reverted back commit which further reverted commit #5e1d74
* Changed environment name to `qa` for consistency.
* Removed `npm run cache` for consistency.
> Revert "fix(mdm): reverted commit 5e1d74 (#174)"

- .eslintrc.json
- src/modules/premium-schedules/premium-schedules.service.ts
Added de-structure rule to keep it inline with `TFS`.
* Added `prefer-destructuring` rule to `eslint`
* Lint fix
> feat(eslint): added destructure eslint rule

- .github/workflows/deployment.yml
- .github/workflows/infrastructure.yml
IaC refactor
* VNET peer: Target environment specific naming convention has been adopted
* Deployment: Import only if API has been created in APIM
* General YML formatting
> refactor(iac): Infrastructure + Deployment

- .github/workflows/deployment.yml
> fix(iac): deployment

- .github/workflows/infrastructure.yml
- package-lock.json
Custom VNET DNS routing
* Added `--dns-servers` flag to `az network vnet create` command for internal DNS routing.
* IaC refactorisation.
* Dependencies updates
> fix(iac): added custom dns for vnet

- Dockerfile
- package-lock.json
- package.json
High CVE has been reported on previous version of Alpine Linux distro
* DockerFile Node and Alpine Linux version update to `node 20.3.1-alpine3.17`
* Dependencies updates
Docker image scanning result only reports `1 Medium`  and `1 Unspecified` vulnerabilities:
> chore(deps): docker node update

- Dockerfile
- docker-compose.yml
High CVE has been reported on previous version of Alpine Linux distro
* DockerFile Node and Alpine Linux version update to `node 20.4-alpine3.17`
* Dependencies updates
Docker image scanning result only reports `1 Unspecified` vulnerability:
> chore(dockerfile): version updates

- .github/workflows/deploy.sh
- package-lock.json
ACR repository name
* Updated threshold days
* Updated repository name
* Dependencies updates.
> fix(iac): ACR

- src/main.module.ts
fixed typo causing the env var for single line log format to not work
> feat(APIM-538): update single line log format env var

- .github/workflows/deployment.yml
Include a summary of the changes and related feature(s) or issue(s).
List all changes made to the codebase.
List any additional fixes or improvements.
> chore(deployment): added missing enviornment variables

- package-lock.json
- src/main.ts
Added a global exceptional handling
* Dependencies updates.
> fix(error): added globalexceptional handling

- src/modules/ods/dto/ods-payloads.dto.ts
- src/modules/ods/ods.service.ts
- test/docs/__snapshots__/get-docs-yaml.api-test.ts.snap
- test/ods/ods.customers.api-test.ts
We were missing API tests for the ODS integration
Add api test and update api docs snapshot test
> feat(GIFT-3543): add api tests for ods integration
